exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('videos').del()
    .then(function () {
      return knex('videos').insert([
        {title: 'A - Adam', url: 'h1sMTI_dmjU', tags: 'stephenFry,alanDavies,johnSessions,dannyBaker,hughLaurie', views: 0, createdAt: new Date()},
        {title: 'A - Astronomy', url: 'ncf2RZ6iTAU', tags: 'stephenFry,alanDavies,billBailey,richHall,jeremyHardy', views: 0, createdAt: new Date()},
        {title: 'A - Aquatic Animals', url: 'KMq0Ab2AsV4', tags: 'stephenFry,alanDavies,cliveAnderson,meeraSyal,billBailey', views: 0, createdAt: new Date()},
        {title: 'A - Atoms', url: 'Tjn_M8sLtBc', tags: 'stephenFry,alanDavies,joBrand,howardGoodall,jeremyHardy', views: 0, createdAt: new Date()},
        {title: 'A - Advertising', url: 'bdUBkPm6-Ic', tags: 'stephenFry,alanDavies,robBrydon,gylesBrandreth,richHall', views: 0, createdAt: new Date()},
        {title: 'A - Antidotes', url: 'HmytVL9WFp0', tags: 'stephenFry,alanDavies,howardGoodall,joBrand,dannyBaker', views: 0, createdAt: new Date()},
        {title: 'A - Arthropods', url: '81huDW-OLik', tags: 'stephenFry,alanDavies,jimmyCarr,jackieClune,joBrand', views: 0, createdAt: new Date()},
        {title: 'A - Albania', url: '-Uy30onZ3Pw', tags: 'stephenFry,alanDavies,lindaSmith,seanLock,cliveAnderson', views: 0, createdAt: new Date()},
        {title: 'A - Antelopes', url: 'QdHntnzt-ks', tags: 'stephenFry,alanDavies,daveGorman,jeremyHardy,joBrand', views: 0, createdAt: new Date()},
        {title: 'A - Aviation', url: '6X5JigfXr6w', tags: 'stephenFry,alanDavies,juliaMorris,peterSerafinowicz,richHall', views: 0, createdAt: new Date()},
        {title: 'A - Arts', url: 'YnOzyO38cR4', tags: 'stephenFry,alanDavies,richardEGrant,billBailey,lindaSmith', views: 0, createdAt: new Date()},
        {title: 'A - Advent', url: 'nbzpq2Nd6wo', tags: 'stephenFry,alanDavies,phillJupitus,seanLock,johnSessions', views: 0, createdAt: new Date()},
        {title: 'B - Birds', url: 'aNgMncOqlA8', tags: 'stephenFry,alanDavies,philKay,richHall,joBrand', views: 0, createdAt: new Date()},
        {title: 'B - Blue', url: 'fgAURVO28Ok', tags: 'stephenFry,alanDavies,joBrand,billBailey,seanLock', views: 0, createdAt: new Date()},
        {title: 'B - Bombs', url: '-qnLhPt71Zo', tags: 'stephenFry,alanDavies,cliveAnderson,phillJupitus,richHall', views: 0, createdAt: new Date()},
        {title: 'B - Bible', url: 'cR94D4jXAaE', tags: 'stephenFry,alanDavies,jeremyHardy,jeremyClarkson,barryCryer', views: 0, createdAt: new Date()},
        {title: 'B - Bears', url: 'fkO3rNNr0HQ', tags: 'stephenFry,alanDavies,jimmyCarr,joBrand,billBailey', views: 0, createdAt: new Date()},
        {title: 'B - Beavers', url: '4Njfk0qqM24', tags: 'stephenFry,alanDavies,annekaRice,seanLock,billBailey', views: 0, createdAt: new Date()},
        {title: 'B - Biscuits', url: 'icnTS9CjLD0', tags: 'stephenFry,alanDavies,arthurSmith,daraOBriain,richHall', views: 0, createdAt: new Date()},
        {title: 'B - Bees', url: 'wf3x0NuizVk', tags: 'stephenFry,alanDavies,fredMacAulay,richHall,joBrand', views: 0, createdAt: new Date()},
        {title: 'B - Bats', url: '7JUzqyh22SY', tags: 'stephenFry,alanDavies,josieLawrence,johnSessions,richHall', views: 0, createdAt: new Date()},
        {title: 'B - Bills', url: 'l_2JeqT1jgw', tags: 'stephenFry,alanDavies,cliveAnderson,philKay,johnSessions', views: 0, createdAt: new Date()},
        {title: 'B - Beats', url: 'tv-X7ZSI0uE', tags: 'stephenFry,alanDavies,markGatiss,lindaSmith,seanLock', views: 0, createdAt: new Date()},
        {title: 'B - Birth', url: 'YjLOXBrnTz4', tags: 'stephenFry,alanDavies,markSteel,phillJupitus,richHall', views: 0, createdAt: new Date()},
        {title: 'C - Campanology', url: 'i6VbDkXcgMg', tags: 'stephenFry,alanDavies,robBrydon,billBailey,richHall', views: 0, createdAt: new Date()},
        {title: 'C - Cummingtonite', url: 'POlPJjAq9SI', tags: 'stephenFry,alanDavies,doonMackichan,arthurSmith,andyHamilton', views: 0, createdAt: new Date()},
        {title: 'C - Common Knowledge', url: '54K1m86CVQM', tags: 'stephenFry,alanDavies,roryMcGrath,jimmyCarr,seanLock', views: 0, createdAt: new Date()},
        {title: 'C - Cheating', url: 'pQ35yAzSm1A', tags: 'stephenFry,alanDavies,jeremyClarkson,alexanderArmstrong,johnSessions', views: 0, createdAt: new Date()},
        {title: "C - Cat's Eyes", url: '7Quyte7zN70', tags: 'stephenFry,alanDavies,joBrand,seanLock,richHall', views: 0, createdAt: new Date()},
        {title: 'C - Cockneys', url: 'rmUo7joFEDM', tags: 'stephenFry,alanDavies,phillJupitus,billBailey,roryMcGrath', views: 0, createdAt: new Date()},
        {title: 'C - Constellations', url: 's6UmqCDmPdE', tags: 'stephenFry,alanDavies,seanLock,richHall,jeremyClarkson', views: 0, createdAt: new Date()},
        {title: 'C - Corby', url: '8BwNw5yqLJU', tags: 'stephenFry,alanDavies,davidMitchell,billBailey,phillJupitus', views: 0, createdAt: new Date()},
        {title: 'C - Creatures', url: '45-VhINIicY', tags: 'stephenFry,alanDavies,helenAtkinsonWood,andyHamilton,billBailey', views: 0, createdAt: new Date()},
        {title: 'C - Cleve Crudgington', url: 'XIFr2b9lVwY', tags: 'stephenFry,alanDavies,markSteel,cliveAnderson,johnSessions', views: 0, createdAt: new Date()},
        {title: 'C - Carnival', url: 'aG_OLL9mt1c', tags: 'stephenFry,alanDavies,phillJupitus,cliveAnderson,joBrand', views: 0, createdAt: new Date()},
        {title: 'C - Combustion', url: 'FoAGk6HRSyg', tags: 'stephenFry,alanDavies,daraOBriain,phillJupitus,billBailey', views: 0, createdAt: new Date()},
        {title: 'D - Danger', url: 'YgL9B54mz_A', tags: 'stephenFry,alanDavies,seanLock,jimmyCarr,joBrand', views: 0, createdAt: new Date()},
        {title: 'D - Discoveries', url: 'dc3nyRvDqfY', tags: 'stephenFry,alanDavies,cliveAnderson,arthurSmith,vicReeves', views: 0, createdAt: new Date()},
        {title: 'D - Dogs', url: 'hChnR9jShUQ', tags: 'stephenFry,alanDavies,jeremyClarkson,neilMullarkey,lizaTarbuck', views: 0, createdAt: new Date()},
        {title: 'D - Dictionaries', url: 'HgPSXlvgAYw', tags: 'stephenFry,alanDavies,ronniAncona,roryBremner,phillJupitus', views: 0, createdAt: new Date()},
        {title: 'D - Death', url: 'z905DfZ8NZc', tags: 'stephenFry,alanDavies,cliveAnderson,seanLock,andyParsons', views: 0, createdAt: new Date()},
        {title: 'D - Drinks', url: 'OthOSzpqDLM', tags: 'stephenFry,alanDavies,jimmyCarr,phillJupitus,johnSessions', views: 0, createdAt: new Date()},
        {title: 'D - Differences', url: 'lGPDag4X3D0', tags: 'stephenFry,alanDavies,joBrand,julianClary,daraOBriain', views: 0, createdAt: new Date()},
        {title: 'D - Descendants', url: '6XaFftJwlfM', tags: 'stephenFry,alanDavies,richHall,phillJupitus,jonathanRoss', views: 0, createdAt: new Date()},
        {title: 'D - Doves', url: 'qjDNAw2xyOk', tags: 'stephenFry,alanDavies,andyHamilton,davidMitchell,johnSessions', views: 0, createdAt: new Date()},
        {title: 'D - Divination', url: '94QYI8OVEsc', tags: 'stephenFry,alanDavies,graemeGarden,phillJupitus,johnnyVaughan', views: 0, createdAt: new Date()},
        {title: 'D - Deprivation', url: 'fv7aw1A6yGY', tags: 'stephenFry,alanDavies,rogerMcGough,vicReeves,markSteel', views: 0, createdAt: new Date()},
        {title: 'D - Domesticity', url: 'FHqnhehzPjM', tags: 'stephenFry,alanDavies,joBrand,phillJupitus,jessicaStevenson', views: 0, createdAt: new Date()},
        {title: 'D - December', url: 'j1TjoS_UDIo', tags: 'stephenFry,alanDavies,joBrand,richHall,daraOBriain', views: 0, createdAt: new Date()},
        {title: 'E - Engineering', url: 'Z4F0GkcWuwQ', tags: 'stephenFry,alanDavies,billBailey,robBrydon,jimmyCarr', views: 0, createdAt: new Date()},
        {title: 'E - Electricity', url: 'j6NOYQBU7sA', tags: 'stephenFry,alanDavies,joBrand,richHall,seanLock', views: 0, createdAt: new Date()},
        {title: 'E - Eating', url: 'pObUd8Io0RA', tags: 'stephenFry,alanDavies,jimmyCarr,phillJupitus,johnnyVegas', views: 0, createdAt: new Date()},
        {title: 'E - Exploration', url: 'a_jxeigax1Y', tags: 'stephenFry,alanDavies,billBailey,richHall,seanLock', views: 0, createdAt: new Date()},
        {title: 'E - Europe', url: 'gU5y11geyak', tags: 'stephenFry,alanDavies,phillJupitus,davidMitchell,daraOBriain', views: 0, createdAt: new Date()},
        {title: 'E - Everything, Etc.', url: 'z-xcfrmY2T0', tags: 'stephenFry,alanDavies,cliveAnderson,jeremyClarkson,vicReeves', views: 0, createdAt: new Date()},
        {title: 'E - Espionage', url: 'pnqRk3iyB9U', tags: 'stephenFry,alanDavies,cliveAnderson,joBrand,vicReeves', views: 0, createdAt: new Date()},
        {title: 'E - Eyes and Ears', url: 'nq18LAWLU5E', tags: 'stephenFry,alanDavies,jimmyCarr,phillJupitus,davidMitchell', views: 0, createdAt: new Date()},
        {title: 'E - Entertainment', url: '7jLW33Zw7JA', tags: 'stephenFry,alanDavies,billBailey,joBrand,jeremyClarkson', views: 0, createdAt: new Date()},
        {title: 'E - England', url: 'atxFIPfUXIs', tags: 'stephenFry,alanDavies,charlieHigson,phillJupitus,seanLock', views: 0, createdAt: new Date()},
        {title: 'E - Endings', url: 'g1ULAuX5Jug', tags: 'stephenFry,alanDavies,jimmyCarr,doonMackichan,daraOBriain', views: 0, createdAt: new Date()},
        {title: 'E - Empire', url: '0kE9tyqKllE', tags: 'stephenFry,alanDavies,billBailey,joBrand,seanLock', views: 0, createdAt: new Date()},
        {title: 'F - Families', url: 'qq85CcBxnm8', tags: 'stephenFry,alanDavies,ronniAncona,davidMitchell,terryWogan', views: 0, createdAt: new Date()},
        {title: 'F - Fire and Freezing', url: 'qo-IKkt3tLY', tags: 'stephenFry,alanDavies,cliveAnderson,robBrydon,domJoly', views: 0, createdAt: new Date()},
        {title: 'F - Flotsam and Jetsam', url: 'nPGiskpU8_0', tags: 'stephenFry,alanDavies,robBrydon,andyHamilton,charlieHigson', views: 0, createdAt: new Date()},
        {title: 'F - Fight or Flight', url: 'rP2jR8raOJU', tags: 'stephenFry,alanDavies,pamAyres,seanLock,johnnyVegas', views: 0, createdAt: new Date()},
        {title: 'F - France', url: '6y75WPvVMKU', tags: 'stephenFry,alanDavies,joBrand,hughDennis,phillJupitus', views: 0, createdAt: new Date()},
        {title: 'F - Fakes and Frauds', url: 'e__WpB9Nqw0', tags: 'stephenFry,alanDavies,marcusBrigstocke,jimmyCarr,seanLock', views: 0, createdAt: new Date()},
        {title: 'F - Fingers and Fumbs', url: '5lhWJHAjTCs', tags: 'stephenFry,alanDavies,joBrand,phillJupitus,daraOBriain', views: 0, createdAt: new Date()},
        {title: 'F - Fashion', url: 'fEU9YsnBFDo', tags: 'stephenFry,alanDavies,cliveAnderson,richHall,reginaldDHunter', views: 0, createdAt: new Date()},
        {title: 'F - The Future', url: 'I6RkXsqGCZk', tags: 'stephenFry,alanDavies,robBrydon,seanLock,benMiller', views: 0, createdAt: new Date()},
        {title: 'F - Flora and Fauna', url: 'P9D3FlYxeOM', tags: 'stephenFry,alanDavies,joBrand,jimmyCarr,johnSergeant', views: 0, createdAt: new Date()},
        {title: 'F - Film', url: 'NvcWkWzaX3E', tags: 'stephenFry,alanDavies,davidMitchell,johnSessions,emmaThompson', views: 0, createdAt: new Date()},
        {title: 'F - Food', url: '8h3W5fBE5gc', tags: 'stephenFry,alanDavies,jimmyCarr,richHall,davidMitchell', views: 0, createdAt: new Date()},
        {title: 'G - Gardens', url: '6zq7sey8rCc', tags: 'stephenFry,alanDavies,robBrydon,davidMitchell,daraOBriain', views: 0, createdAt: new Date()},
        {title: 'G - Ganimals', url: 'C0wbIuhxaQ4', tags: 'stephenFry,alanDavies,billBailey,johnHodgman,seanLock,sandiToksvig', views: 0, createdAt: new Date()},
        {title: 'G - Games', url: 'MiNw8bm2gww', tags: 'stephenFry,alanDavies,phillJupitus,seanLock,lizaTarbuck', views: 0, createdAt: new Date()},
        {title: 'G - Geography', url: 'R93Bl6wXDOg', tags: 'stephenFry,alanDavies,joBrand,robBrydon,jimmyCarr', views: 0, createdAt: new Date()},
        {title: 'G - Groovy', url: 'wFK6CDVghUU', tags: 'stephenFry,alanDavies,billBailey,leeMack,davidTennant', views: 0, createdAt: new Date()},
        {title: 'G - Genius', url: 'o-hJ4WEhxgM', tags: 'stephenFry,alanDavies,davidMitchell,grahamNorton,daraOBriain', views: 0, createdAt: new Date()},
        {title: 'G - Girls and Boys', url: 'AlBXau1u5Wg', tags: 'stephenFry,alanDavies,ronniAncona,jackDee,sandiToksvig', views: 0, createdAt: new Date()},
        {title: 'G - Germany', url: '1AMYIheppLU', tags: 'stephenFry,alanDavies,joBrand,robBrydon,seanLock', views: 0, createdAt: new Date()},
        {title: 'G - Gallimaufrey', url: 'Imxc7yPscbw', tags: 'stephenFry,alanDavies,hughDennis,andyHamilton,phillJupitus', views: 0, createdAt: new Date()},
        {title: 'G - Greats', url: 'PdnRFO0ukU0', tags: 'stephenFry,alanDavies,joBrand,seanLock,davidMitchell', views: 0, createdAt: new Date()},
        {title: 'G - Gifts', url: 'nQdj0-tvEPM', tags: 'stephenFry,alanDavies,cliveAnderson,jimmyCarr,janRavens', views: 0, createdAt: new Date()},
        {title: 'G - Gravity', url: 'OuUE5fOcla8', tags: 'stephenFry,alanDavies,billBailey,richHall,barryHumphries', views: 0, createdAt: new Date()},
        {title: 'G - Gothic', url: 'TviFSgopL3U', tags: 'stephenFry,alanDavies,jimmyCarr,jackDee,suePerkins', views: 0, createdAt: new Date()},
        {title: 'G - Greeks', url: '54bqxpFn608', tags: 'stephenFry,alanDavies,cliveAnderson,richHall,phillJupitus', views: 0, createdAt: new Date()},
        {title: 'G - Green', url: 'E3mF7Fe9bEw', tags: 'stephenFry,alanDavies,billBailey,dannyBaker,jeremyClarkson', views: 0, createdAt: new Date()},
        {title: 'G - Geometry', url: '_WrbSHKoL_c', tags: 'stephenFry,alanDavies,robBrydon,davidMitchell,johnnyVegas', views: 0, createdAt: new Date()},
        {title: 'H - Hodge Podge', url: 'iLZjTpvdW_g', tags: 'stephenFry,alanDavies,jackDee,phillJupitus,rossNoble', views: 0, createdAt: new Date()},
        {title: 'H - H Anatomy', url: 'm7MLf_P0_Cs', tags: 'stephenFry,alanDavies,suePerkins,billBailey,gylesBrandreth', views: 0, createdAt: new Date()},
        {title: 'H - Hoaxes', url: 'JUHszXyHbfc', tags: 'stephenFry,alanDavies,seanLock,dannyBaker,davidMitchell', views: 0, createdAt: new Date()},
        {title: 'H - Humans', url: 'w2l2YTVOaZk', tags: 'stephenFry,alanDavies,joBrand,jimmyCarr,jackDee', views: 0, createdAt: new Date()},
        {title: 'H - H Animals', url: 'B35bi6fKkXE', tags: 'stephenFry,alanDavies,seanLock,rossNoble,rubyWax', views: 0, createdAt: new Date()},
        {title: 'H - Happiness', url: 'snQUZhWI2-s', tags: 'stephenFry,alanDavies,richHall,andyHamilton,phillJupitus', views: 0, createdAt: new Date()},
        {title: 'H - Horrible', url: 'DiLOod8wGpY', tags: 'stephenFry,alanDavies,chrisAddison,seanLock,daraOBriain', views: 0, createdAt: new Date()},
        {title: 'H - Hypothetical', url: 'zYg7tn2N38o', tags: 'stephenFry,alanDavies,johnLloyd,sandiToksvig,johnnyVegas', views: 0, createdAt: new Date()},
        {title: 'H - House and Home', url: 'KP6THdOjzIs', tags: 'stephenFry,alanDavies,billBailey,dannyBaker,eddieIzzard', views: 0, createdAt: new Date()},
        {title: 'H - Health and Safety', url: '8bQQpdMzzLg', tags: 'stephenFry,alanDavies,jeremyClarkson,davidMitchell,rossNoble', views: 0, createdAt: new Date()},
        {title: 'H - Highs and Lows', url: 'vbVzDo12kMw', tags: 'stephenFry,alanDavies,robBrydon,fredMacAulay,sandiToksvig', views: 0, createdAt: new Date()},
        {title: 'H - Horses and Hunting', url: 'XZMBjx1Zvvo', tags: 'stephenFry,alanDavies,clareBalding,jimmyCarr,daraOBriain', views: 0, createdAt: new Date()},
        {title: 'H - Holidays', url: 'SQTJ7ryargc', tags: 'stephenFry,alanDavies,billBailey,robBrydon,richHall', views: 0, createdAt: new Date()},
        {title: 'H - Hocus Pocus', url: '3ZaudVd9WAY', tags: 'stephenFry,alanDavies,leeMack,grahamNorton,danielRadcliffe', views: 0, createdAt: new Date()},
        {title: 'H - Hypnosis, Hallucinations And Hysteria', url: 'oSKNqpRgjq8', tags: 'stephenFry,alanDavies,ronniAncona,phillJupitus,robertWebb', views: 0, createdAt: new Date()},
        {title: 'H - History', url: 'iO1_l2j0Y8w', tags: 'stephenFry,alanDavies,robBrydon,davidMitchell,sandiToksvig', views: 0, createdAt: new Date()},
        {title: 'I - I-Spy', url: 'mG696JqzHsE', tags: 'stephenFry,alanDavies,jimmyCarr,leeMack,sandiToksvig', views: 0, createdAt: new Date()},
        {title: 'I - International', url: 'Fc95bv76Feo', tags: 'stephenFry,alanDavies,jackDee,billBailey,davidMitchell', views: 0, createdAt: new Date()},
        {title: 'I - Imbroglio', url: 'Dab_LLxpxSg', tags: 'stephenFry,alanDavies,johnBishop,frankSkinner,seanLock', views: 0, createdAt: new Date()},
        {title: 'I - Indecision', url: 'sweQ3KkD6HY', tags: 'stephenFry,alanDavies,jimmyCarr,richHall,phillJupitus', views: 0, createdAt: new Date()},
        {title: 'I - Invertebrates', url: 'Y1OWDfXU7So', tags: 'stephenFry,alanDavies,jimmyCarr,sarahMillican,johnnyVegas', views: 0, createdAt: new Date()},
        {title: 'I - Inventive', url: 'jv4YTQdTyKg', tags: 'stephenFry,alanDavies,ninaConti,seanLock,billBailey', views: 0, createdAt: new Date()},
        {title: 'I - Incomprehensible', url: 'Nuv6kOdiSBY', tags: 'stephenFry,alanDavies,rossNoble,suePerkins,brianCox', views: 0, createdAt: new Date()},
        {title: 'I - Inland Revenue', url: '-MuiL9TR6BU', tags: 'stephenFry,alanDavies,sandiToksvig,alMurray,daraOBriain', views: 0, createdAt: new Date()},
        {title: 'I - Infantile', url: 'eNk6HKrKxtQ', tags: 'stephenFry,alanDavies,daveGorman,ronniAncona,leeMack', views: 0, createdAt: new Date()},
        {title: 'I - Intelligence', url: '29fAKUvneyk', tags: 'stephenFry,alanDavies,davidMitchell,joBrand,phillJupitus', views: 0, createdAt: new Date()},
        {title: 'I - Ice', url: '_TBVFCWKDpk', tags: 'stephenFry,alanDavies,rossNoble,seanLock,brianBlessed', views: 0, createdAt: new Date()},
        {title: 'I - Immortal Bard', url: '1jkvzR_iOVs', tags: 'stephenFry,alanDavies,davidMitchell,suePerkins,billBailey', views: 0, createdAt: new Date()},
        {title: 'I - Idleness', url: 'MRP9q37npAw', tags: 'stephenFry,alanDavies,rossNoble,daraOBriain,jeremyClarkson', views: 0, createdAt: new Date()},
        {title: 'I - Inequality', url: 'W9J_S-MHh3M', tags: 'stephenFry,alanDavies,cliveAnderson,sandiToksvig,henningWehn', views: 0, createdAt: new Date()},
        {title: 'I - Illness', url: 'zQnc1XcnNKQ', tags: 'stephenFry,alanDavies,joBrand,benGoldacre,andyHamilton', views: 0, createdAt: new Date()},
        {title: 'I - Illumination', url: 'Eb12U9vaExg', tags: 'stephenFry,alanDavies,chrisAddison,jackDee,richHall', views: 0, createdAt: new Date()},
        {title: 'J - Jargon', url: '8h0LLD_N9ds', tags: 'stephenFry,alanDavies,billBailey,jimmyCarr,victoriaCorenMitchell', views: 0, createdAt: new Date()},
        {title: 'J - Jam, Jelly and Juice', url: '-HWHjU0uUA8', tags: 'stephenFry,alanDavies,joBrand,suePerkins,lizaTarbuck', views: 0, createdAt: new Date()},
        {title: 'J - Journeys', url: 'IqugwtZRE1U', tags: 'stephenFry,alanDavies,robBrydon,phillJupitus,calWilson', views: 0, createdAt: new Date()},
        {title: 'J - Jack & Jill', url: 'KMe-t57ri9A', tags: 'stephenFry,alanDavies,katyBrand,davidMitchell,suePerkins', views: 0, createdAt: new Date()},
        {title: 'J - J-Places', url: 'eIcXG9ud9vU', tags: 'stephenFry,alanDavies,billBailey,susanCalman,sandiToksvig', views: 0, createdAt: new Date()},
        {title: 'J - Joints', url: '5G6-Gb2vq3g', tags: 'stephenFry,alanDavies,jimmyCarr,jackWhitehall,calWilson', views: 0, createdAt: new Date()},
        {title: 'J - Journalism', url: 'rZWoo0ajynY', tags: 'stephenFry,alanDavies,shappiKhorsandi,rossNoble,johnnyVegas', views: 0, createdAt: new Date()},
        {title: 'J - Jumble', url: 'wu6uwF3J1Nw', tags: 'stephenFry,alanDavies,joBrand,daraOBriain,johnSessions', views: 0, createdAt: new Date()},
        {title: 'J - Jeopardy', url: 'seMwRkdD8-4', tags: 'stephenFry,alanDavies,rossNoble,suePerkins,juliaZemiro', views: 0, createdAt: new Date()},
        {title: 'J - Jungles', url: 'JwIPyJP_Z5w', tags: 'stephenFry,alanDavies,reginaldDHunter,davidODoherty,gregProops', views: 0, createdAt: new Date()},
        {title: 'J - Jumpers', url: 'RFFI4V6cnjg', tags: 'stephenFry,alanDavies,billBailey,julianClary,rossNoble', views: 0, createdAt: new Date()},
        {title: 'J - Justice', url: '3sxo95Xu3Cw', tags: 'stephenFry,alanDavies,brianCox,rhysDarby,jasonManford', views: 0, createdAt: new Date()},
        {title: 'J - Jobs', url: 'UmkEEL7fcc0', tags: 'stephenFry,alanDavies,richardColes,sarahMillican', views: 0, createdAt: new Date()},
        {title: 'J - Jingle Bells', url: 'ZlzwpF6Zm3o', tags: 'stephenFry,alanDavies,dannyBaker,phillJupitus,sarahMillican', views: 0, createdAt: new Date()},
        {title: 'J - Jolly', url: 'GnC1-HwsBVs', tags: 'stephenFry,alanDavies,robBrydon,timVine,juliaZemiro', views: 0, createdAt: new Date()},
        {title: 'J - Just the Job', url: 'f7mqKWrgbxs', tags: 'stephenFry,alanDavies,jeremyClarkson,jasonManford,sandiToksvig', views: 0, createdAt: new Date()},
        {title: 'K - Knees & Knockers', url: 'FwZBEo2JHIw', tags: 'stephenFry,alanDavies,saraPascoe,jackWhitehall,davidMitchell', views: 0, createdAt: new Date()},
        {title: 'K - Kit and Kaboodle', url: '28T2MBFIvUI', tags: 'stephenFry,alanDavies,noelFielding,rossNoble,colinLane', views: 0, createdAt: new Date()},
        {title: 'K - K-Folk', url: 'psjhdmlnnfA', tags: 'stephenFry,alanDavies,katherineRyan,joshWiddicombe,phillJupitus', views: 0, createdAt: new Date()},
        {title: 'K - Knits & Knots', url: 'lRA-vGjtSOc', tags: 'stephenFry,alanDavies,suePerkins,rossNoble,davidMitchell', views: 0, createdAt: new Date()},
        {title: 'K - Kings', url: '5qxEiUS7Wls', tags: 'stephenFry,alanDavies,jeremyClarkson,jimmyCarr,billBailey', views: 0, createdAt: new Date()},
        {title: 'K - Killers', url: '8fjsA66rHkI', tags: 'stephenFry,alanDavies,sandiToksvig,trevorNoah,jasonManford', views: 0, createdAt: new Date()},
        {title: 'K - Knowledge', url: 'N2aFRBF7QE4', tags: 'stephenFry,alanDavies,grahamLinehan,jimmyCarr,joBrand', views: 0, createdAt: new Date()},
        {title: 'K - Keys', url: 'Fjw9g_PRCXU', tags: 'stephenFry,alanDavies,isySuttie,timMinchin,billBailey', views: 0, createdAt: new Date()},
        {title: 'K - Kinetic', url: '-mzRTTTZgdA', tags: 'stephenFry,alanDavies,joBrand,marcusBrigstocke,dannyBaker', views: 0, createdAt: new Date()},
        {title: 'K - Keeps', url: '-gZ-VgA9leo', tags: 'stephenFry,alanDavies,sarahMillican,jasonManford,billBailey', views: 0, createdAt: new Date()},
        {title: 'K - Kinky', url: 'eaUJJpp3X0Y', tags: 'stephenFry,alanDavies,janetStreetPorter,sandiToksvig,johnnyVegas', views: 0, createdAt: new Date()},
        {title: 'K - Knights and Knaves', url: 'BLmUrTVbxUo', tags: 'stephenFry,alanDavies,victoriaCorenMitchell,suePerkins,richardColes', views: 0, createdAt: new Date()},
        {title: 'K - Kitchen Sink', url: 'b8ljGoWvALU', tags: 'stephenFry,alanDavies,victoriaWood,richardOsman,jasonManford', views: 0, createdAt: new Date()},
        {title: 'K - Kris Kringle', url: 'ffE_cG-S5LY', tags: 'stephenFry,alanDavies,joBrand,brendanOCarroll,phillJupitus', views: 0, createdAt: new Date()},
        {title: 'K - Kitsch', url: 'Qtmd1byR8Ps', tags: 'stephenFry,alanDavies,suePerkins,reginaldDHunter,jimmyCarr', views: 0, createdAt: new Date()},
        {title: 'K - Kaleidoscope', url: '3I54CRXS23s', tags: 'stephenFry,alanDavies,susanCalman,sandiToksvig,lizaTarbuck', views: 0, createdAt: new Date()},
        {title: 'L - Location, Location, Location', url: 'yUS96YyisoE', tags: 'stephenFry,alanDavies,jasonManford,johnnyVegas,aislingBea', views: 0, createdAt: new Date()},
        {title: 'L - Literature', url: 'SzPiW8FtvGQ', tags: 'stephenFry,alanDavies,lloydLangford,jackWhitehall,victoriaCorenMitchell', views: 0, createdAt: new Date()},
        {title: 'L - Levity', url: 'ffI9LeTM_8o', tags: 'stephenFry,alanDavies,suePerkins,frankSkinner,joshWiddicombe', views: 0, createdAt: new Date()},
        {title: 'L - Liblabble', url: 'hrNjD2VUV3k', tags: 'stephenFry,alanDavies,richardColes,saraPascoe,billBailey', views: 0, createdAt: new Date()},
        {title: 'L - Lethal', url: 'afaw_Y6BQuk', tags: 'stephenFry,alanDavies,billBailey,sandiToksvig,jasonManford', views: 0, createdAt: new Date()},
        {title: 'L - Lovely', url: 'EY2gE8NTLdw', tags: 'stephenFry,alanDavies,aislingBea,tonyHawks,joshWiddicombe', views: 0, createdAt: new Date()},
        {title: 'L - Lying', url: '0PzNDMCT0rg', tags: 'stephenFry,alanDavies,adamHills,saraPascoe,jackWhitehall', views: 0, createdAt: new Date()},
        {title: 'L - Lumped Together', url: '86n5k9AGcEA', tags: 'stephenFry,alanDavies,davidMitchell,ronniAncona,jimmyCarr', views: 0, createdAt: new Date()},
        {title: 'L - No-L', url: 'PFu7CWLPwJc', tags: 'stephenFry,alanDavies,carrieFisher,billBailey,jimmyCarr', views: 0, createdAt: new Date()},
        {title: 'L - Lucky Losers', url: '8US3Snx5L3c', tags: 'stephenFry,alanDavies,dannyBaker,sandiToksvig,jeremyClarkson', views: 0, createdAt: new Date()},
        {title: 'L - Little and Large', url: 'SBmb-gE-afU', tags: 'stephenFry,alanDavies,phillJupitus,richardOsman,lucyPorter', views: 0, createdAt: new Date()},
        {title: 'L - Long Lost', url: 'aUL8rJN1_Ak', tags: 'stephenFry,alanDavies,jimmyCarr,claudiaODoherty,suggs', views: 0, createdAt: new Date()},
        {title: 'L - Landmarks', url: 'q37IylYd2NY', tags: 'stephenFry,alanDavies,joBrand,colinLane,davidMitchell', views: 0, createdAt: new Date()},
        {title: 'L - Ladies and Gents', url: 'NKCEXIzLpAk', tags: 'stephenFry,alanDavies,kathyLette,rossNoble,suePerkins', views: 0, createdAt: new Date()},
        {title: 'L - L-Animals', url: 'v9Id_YeTR2s', tags: 'stephenFry,alanDavies,colinLane,sarahMillican,rossNoble', views: 0, createdAt: new Date()},
        {title: 'L - Lenses', url: 'LeQwrEsCjnI', tags: 'stephenFry,alanDavies,joBrand,phillJupitus,joshWiddicombe', views: 0, createdAt: new Date()},
        {title: 'M - A Medley of Maladies', url: 'eVrZlVQD8qk', tags: 'stephenFry,alanDavies,mattLucas,rossNoble,lucyPorter', views: 0, createdAt: new Date()},
        {title: 'M - Military Matters', url: '-DoRQC1JMyw', tags: 'stephenFry,alanDavies,jimmyCarr,jeremyClarkson,sheilaHancock', views: 0, createdAt: new Date()},
        {title: 'M - M Places', url: '5XNLdWB0R9A', tags: 'stephenFry,alanDavies,davidMitchell,suePerkins,samiShah', views: 0, createdAt: new Date()},
        {title: 'M - Miscellany', url: 'ipFIxrsYSxs', tags: 'stephenFry,alanDavies,noelFielding,rhodGilbert,cariadLloyd', views: 0, createdAt: new Date()},
        {title: 'M - Maths', url: 'NYBB1WfRm84', tags: 'stephenFry,alanDavies,aislingBea,susanCalman,sandiToksvig', views: 0, createdAt: new Date()},
        {title: 'M - Marriage and Mating', url: 'QeupPaKSs1k', tags: 'stephenFry,alanDavies,billBailey,joBrand,gregDavies', views: 0, createdAt: new Date()},
        {title: 'M - Middle Muddle', url: 'woPeAy1_Hac', tags: 'stephenFry,alanDavies,aislingBea,dannyBhoy,jimmyCarr', views: 0, createdAt: new Date()},
        {title: 'M - Messing With Your Mind', url: 'QJwy49CdAd4', tags: 'stephenFry,alanDavies,sarahMillican,tommyTiernan,joshWiddicombe', views: 0, createdAt: new Date()},
        {title: 'M - Merriment', url: 'LK_Ojf-OwKQ', tags: 'stephenFry,alanDavies,billBailey,jennyEclair,johnnyVegas', views: 0, createdAt: new Date()},
        {title: 'M - Making a Meal of It', url: 'LAtiBBIKeUo', tags: 'stephenFry,alanDavies,phillJupitus,cariadLloyd,dermotOLeary', views: 0, createdAt: new Date()},
        {title: 'M - Menagerie', url: 'anOqWE6AdEE', tags: 'stephenFry,alanDavies,billBailey,suePerkins,romeshRanganathan', views: 0, createdAt: new Date()},
        {title: 'M - Medieval and Macabre', url: '5uNhxW6eI9A', tags: 'stephenFry,alanDavies,mattLucas,davidMitchell,juliaZemiro', views: 0, createdAt: new Date()},
        {title: 'M - Monster Mash', url: 'zdJ4u8D4eE4', tags: 'stephenFry,alanDavies,phillJupitus,saraPascoe,joshWiddicombe', views: 0, createdAt: new Date()},
        {title: 'M - Messy', url: 'Xh01lzYqG8I', tags: 'stephenFry,alanDavies,noelFielding,eddieKadi,sarahMillican', views: 0, createdAt: new Date()},
        {title: 'M - Mix and Match', url: 'r2eB_m5HxyI', tags: 'stephenFry,alanDavies,jamesAcaster,billBailey,joBrand', views: 0, createdAt: new Date()},
        {title: 'M - Misconceptions', url: 'axazQ_p6KN4', tags: 'stephenFry,alanDavies,chrisAddison,saraCox,suePerkins', views: 0, createdAt: new Date()},
        {title: 'N - Naming Names', url: 'uRdUbTJoscY', tags: 'sandiToksvig,alanDavies,phillJupitus,cariadLloyd,romeshRanganathan', views: 0, createdAt: new Date()},
        {title: 'N - North Norse', url: '3aH-DWK1jg4', tags: 'sandiToksvig,alanDavies,lucyBeaumont,rhodGilbert,jasonManford', views: 0, createdAt: new Date()},
        {title: 'N - Nosey Noisy', url: 'ZeAFY5VJHi4', tags: 'sandiToksvig,alanDavies,aislingBea,rossNoble,coreyTaylor', views: 0, createdAt: new Date()},
        {title: 'N - Noble Rot', url: 'hpWncRcGUEo', tags: 'sandiToksvig,alanDavies,jeremyClarkson,jasonManford,saraPascoe', views: 0, createdAt: new Date()},
        {title: 'N - Not Nearly', url: 'zz1tax6wCao', tags: 'sandiToksvig,alanDavies,gylesBrandreth,jimmyCarr,victoriaCorenMitchell', views: 0, createdAt: new Date()},
        {title: 'N - Night', url: 'kF_Z57FeNCs', tags: 'sandiToksvig,alanDavies,noelFielding,davidMitchell,hollyWalsh', views: 0, createdAt: new Date()},
        {title: 'N - Naked Truth', url: 'eW-d0B5Ljdw', tags: 'sandiToksvig,alanDavies,lollyAdefope,leeMack,richardOsman', views: 0, createdAt: new Date()},
        {title: 'N - Non Sequiturs', url: 'wQharLJ5d70', tags: 'sandiToksvig,alanDavies,phillJupitus,milesJupp,deirdreOKane', views: 0, createdAt: new Date()},
        {title: 'N - Noel', url: 'CNUgOmktNZo', tags: 'sandiToksvig,alanDavies,susanCalman,mattLucas,joshWiddicombe', views: 0, createdAt: new Date()},
        {title: 'N - Nature Nurture', url: 'lJdft9xLePQ', tags: 'sandiToksvig,alanDavies,davidBaddiel,cariadLloyd,rossNoble', views: 0, createdAt: new Date()},
        {title: 'N - Noodles', url: 'yviMKo30Tk0', tags: 'sandiToksvig,alanDavies,cariadLloyd,mattLucas,jerrySpringer', views: 0, createdAt: new Date()},
        {title: 'N - Nonsense', url: 'H63xc1pPuDc', tags: 'sandiToksvig,alanDavies,phillJupitus,nishKumar,hollyWalsh', views: 0, createdAt: new Date()},
        {title: 'N - Naval Navigation', url: 'l2nmTBLL75A', tags: 'sandiToksvig,alanDavies,ronniAncona,jimmyCarr,johnnyVegas', views: 0, createdAt: new Date()},
        {title: 'N - Numbers', url: 'oOWZu_qrrd8', tags: 'sandiToksvig,alanDavies,noelFielding,colinLane,sarahMillican', views: 0, createdAt: new Date()},
        {title: 'N - Next', url: 'GMWsKtaJoG8', tags: 'sandiToksvig,alanDavies,frankieBoyle,rossNoble,lucyPorter', views: 0, createdAt: new Date()},
        {title: 'N - New', url: 'NWUlbYtvCyY', tags: 'sandiToksvig,alanDavies,cliveAnderson,joBrand,jimmyCarr', views: 0, createdAt: new Date()},
        {
          title: 'O - Ologies',
          url: '6-PtlJH24I0',
          tags: 'sandiToksvig,alanDavies,billBailey,phillJupitus,claudiaWinkleman',
          views: 0,
          createdAt: new Date(),
        },
        {
          title: 'O - Organisms',
          url: '18I0P4Jxu-Y',
          tags: 'sandiToksvig,alanDavies,nishKumar,cariadLloyd,hollyWalsh',
          views: 0,
          createdAt: new Date(),
        },
        {
          title: 'O - Oceans',
          url: 'NzvHXbZyv8s',
          tags: 'sandiToksvig,alanDavies,aislingBea,joeLycett,davidMitchell',
          views: 0,
          createdAt: new Date(),
        },
        {
          title: 'O - Over and Ova',
          url: 'khnf1JjDYbU',
          tags: 'sandiToksvig,alanDavies,billBailey,graysonPerry,janRavens',
          views: 0,
          createdAt: new Date(),
        },
        {
          title: 'O - Odorous and Odious',
          url: '1mQWOrf01AY',
          tags: 'sandiToksvig,alanDavies,nishKumar,rossNoble,sallyPhillips',
          views: 0,
          createdAt: new Date(),
        },
        {
          title: 'O - Odds and Ends',
          url: 'v_otjEbhGEY',
          tags: 'sandiToksvig,alanDavies,mattLucas,romeshRanganathan,lizaTarbuck',
          views: 0,
          createdAt: new Date(),
        },
        {
          title: 'O - Opposites',
          url: 'KHKJubqckpc',
          tags: 'sandiToksvig,alanDavies,jimmyCarr,colinLane,saraPascoe',
          views: 0,
          createdAt: new Date(),
        },
        {
          title: 'O - Operations',
          url: 'tciCFItoB3s',
          tags: 'sandiToksvig,alanDavies,billBailey,rhodGilbert,katherineRyan',
          views: 0,
          createdAt: new Date(),
        },
        {
          title: 'O - O Christmas',
          url: '3kkoe-UoArs',
          tags: 'sandiToksvig,alanDavies,jasonManford,romeshRanganathan,hollyWalsh',
          views: 0,
          createdAt: new Date(),
        },
        {
          title: 'O - Origins and Openings',
          url: 'nxgkc53X1kI',
          tags: 'sandiToksvig,alanDavies,susanCalman,richHall,joshWiddicombe',
          views: 0,
          createdAt: new Date(),
        },
        {
          title: 'O - Objects and Ornaments',
          url: 'b0KD271FMSw',
          tags: 'sandiToksvig,alanDavies,aliceLevine,cariadLloyd,sarahMillican',
          views: 0,
          createdAt: new Date(),
        },
        {
          title: 'O - The Occult',
          url: 'a7-eurOWxS0',
          tags: 'sandiToksvig,alanDavies,aislingBea,russellBrand,noelFielding',
          views: 0,
          createdAt: new Date(),
        },
        {
          title: 'O - Omnishambles',
          url: 'cie750Ha44E',
          tags: 'sandiToksvig,alanDavies,stephenKAmos,callyBeaton,joshWiddicombe',
          views: 0,
          createdAt: new Date(),
        },
        {
          title: 'O - Oddballs',
          url: 'zCIEgkiG4Do',
          tags: 'sandiToksvig,alanDavies,jimmyCarr,victoriaCorenMitchell,jasonManford',
          views: 0,
          createdAt: new Date(),
        },
        {
          title: 'O - Occupations and Offices',
          url: 'W2Y4Gi7GNXw',
          tags: 'sandiToksvig,alanDavies,davidMitchell,deirdreOKane,richardOsman',
          views: 0,
          createdAt: new Date(),
        },
      ]);
    });
};
